// Generated by CoffeeScript 1.7.1

/*
    al-with="some.long.path"
 */

(function() {
  alight.directives.al["with"] = {
    priority: 500,
    init: function(element, name, scope, env) {
      var self;
      self = alight.directives.al["if"].init(element, name, scope, env);
      self.insertBlock = function(value) {
        if (self.child) {
          self.removeBlock();
        }
        if (!f$.isObject(value)) {
          return;
        }
        self.item = f$.clone(self.base_element);
        self.insertDom(self.top_element, self.item);
        self.child = alight.Scope({
          prototype: value,
          root: scope.$system.root,
          attachParent: scope
        });
        return alight.applyBindings(self.child, self.item, {
          skip_attr: env.skippedAttr()
        });
      };
      return self;
    }
  };

}).call(this);
